export { BrowserView, type BrowserViewProps } from "./browser-view"
export { ArtifactsView } from "./artifacts-view"
export { getCanvasViewMeta, CANVAS_VIEW_REGISTRY, type CanvasViewMeta } from "./registry"
export { default as UnifiedSearch } from "./panels/unified-search"
export { default as WorkspaceDashboard } from "./panels/workspace-dashboard"
export { default as MemoryGraph } from "./panels/memory-graph"
export { default as KnowledgeGraph } from "./panels/knowledge-graph"
export { default as CausalTrace } from "./panels/causal-trace"
export { default as SessionTimeline } from "./panels/session-timeline"
export { default as VectorExplorer } from "./panels/vector-explorer"
export { default as QueryPlayground } from "./panels/query-playground"
