/**
 * Eulinx DesignTokens generator.
 *
 * Consumes the `TokenSet` from `src/ui/tokens/tokens.source.ts` and emits:
 *   - `src/ui/tokens/tokens.css`        (GENERATED, all --Eulinx-* custom properties)
 *   - `src/ui/tokens/tokens.ts`         (EulinxTokenName union + typed token() helper)
 *   - `src/ui/tokens/contrast-report.json` (per-theme contrast audit)
 *
 * Run with:  tsx scripts/generate-tokens.ts
 *   (or: node --experimental-strip-types scripts/generate-tokens.ts)
 *
 * The generator FAILS the build if:
 *   - any semantic color contrast pair drops below its AA floor, or
 *   - (documented) the emitted files are stale vs the source — rerun the generator.
 *
 * Staleness guard: we record a source hash + a generatedAt timestamp inside a
 * small sidecar file `tokens.generated.json`. On each run we compare the current
 * source hash to the recorded one; if they differ the previously emitted files
 * are considered stale and must be regenerated (the files ARE regenerated here,
 * but CI can run this in --check mode to enforce it without file-watching).
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createHash } from "node:crypto";
import {
  tokenSet,
  THEME_DARK,
  THEME_LIGHT,
  THEME_IDS,
  type PrimitiveToken,
  type SemanticToken,
  type ComponentToken,
  type TokenSet,
  type ThemeId,
} from "../src/ui/tokens/tokens.source.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, "..");
const TOKENS_DIR = resolve(ROOT, "src/ui/tokens");

const CSS_PATH = resolve(TOKENS_DIR, "tokens.css");
const TS_PATH = resolve(TOKENS_DIR, "tokens.ts");
const REPORT_PATH = resolve(TOKENS_DIR, "contrast-report.json");
const SIDECAR_PATH = resolve(TOKENS_DIR, "tokens.generated.json");

const AA_TEXT_FLOOR = 4.5;
const AA_UI_FLOOR = 3.0;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function headerComment(generatedAt: string): string {
  return [
    "/*",
    " * GENERATED FILE — DO NOT EDIT.",
    " * Generated by scripts/generate-tokens.ts from",
    ` * ${tokenSet.generatedFrom} (token set v${tokenSet.version}).`,
    ` * Generated at ${generatedAt}.`,
    " * Edit the source and re-run the generator instead.",
    " */",
    "",
  ].join("\n");
}

function fail(message: string): never {
  process.stderr.write(`\n[tokens] BUILD FAILED: ${message}\n`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// CSS generation
// ---------------------------------------------------------------------------

function primitiveValueForTheme(p: PrimitiveToken, theme: ThemeId): string {
  if (p.themeScope === "themed" && p.themeValues) {
    const v = p.themeValues[theme];
    if (v === undefined) fail(`Primitive ${p.name} has no theme value for ${theme}.`);
    return v;
  }
  return p.value;
}

function generateCss(set: TokenSet): string {
  const now = new Date().toISOString();
  const lines: string[] = [headerComment(now)];

  // Layer 1 primitives — :root defaults for Eulinx-dark.
  lines.push(`/* Layer 1: primitives (defaults = ${THEME_DARK}) */`);
  lines.push(":root {");
  for (const p of set.primitives) {
    const v = primitiveValueForTheme(p, THEME_DARK);
    lines.push(`  ${p.name}: ${v};`);
  }
  // Layer 2 semantic + Layer 3 component resolve to their dark bindings.
  for (const s of set.semantics) {
    lines.push(`  ${s.name}: var(${s.bindings[THEME_DARK]});`);
  }
  for (const c of set.components) {
    lines.push(`  ${c.name}: var(${c.binding});`);
  }
  lines.push("}");
  lines.push("");

  // Light theme overrides (only color + elev are themed).
  lines.push(`/* Light theme overrides (color + elev only) */`);
  lines.push(`[data-theme="${THEME_LIGHT}"] {`);
  for (const p of set.primitives) {
    if (p.themeScope === "themed") {
      const v = primitiveValueForTheme(p, THEME_LIGHT);
      lines.push(`  ${p.name}: ${v};`);
    }
  }
  for (const s of set.semantics) {
    lines.push(`  ${s.name}: var(${s.bindings[THEME_LIGHT]});`);
  }
  lines.push("}");
  lines.push("");

  // Also support a class-based toggle for environments that prefer it.
  lines.push(`/* Class-based light theme (same overrides) */`);
  lines.push(`.theme-${THEME_LIGHT} {`);
  for (const p of set.primitives) {
    if (p.themeScope === "themed") {
      const v = primitiveValueForTheme(p, THEME_LIGHT);
      lines.push(`  ${p.name}: ${v};`);
    }
  }
  for (const s of set.semantics) {
    lines.push(`  ${s.name}: var(${s.bindings[THEME_LIGHT]});`);
  }
  lines.push("}");
  lines.push("");

  // Reduced-motion override: collapse duration tokens to 0ms.
  lines.push("/* Reduced-motion: all motion durations collapse to 0ms */");
  lines.push("@media (prefers-reduced-motion: reduce) {");
  lines.push("  :root {");
  for (const p of set.primitives) {
    if (p.category === "duration") {
      lines.push(`    ${p.name}: 0ms;`);
    }
  }
  lines.push("  }");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// TS generation
// ---------------------------------------------------------------------------

function generateTs(set: TokenSet): string {
  const now = new Date().toISOString();
  const allNames = [
    ...set.primitives.map((p) => p.name),
    ...set.semantics.map((s) => s.name),
    ...set.components.map((c) => c.name),
  ];

  const unionMembers = allNames.map((n) => `  | "${n}"`).join("\n");

  return [
    "/*",
    " * GENERATED FILE — DO NOT EDIT.",
    " * Generated by scripts/generate-tokens.ts from",
    ` * ${set.generatedFrom} (token set v${set.version}).`,
    ` * Generated at ${now}.`,
    " * Edit the source and re-run the generator instead.",
    " */",
    "",
    'import type { EulinxTokenName as EulinxTokenNameSource } from "./tokens.source";',
    "",
    "/** Every legal DesignToken name. A typo is a compile error. */",
    "export type EulinxTokenName =",
    unionMembers,
    ";",
    "",
    "/**",
    " * The only sanctioned way to read a token from TSX.",
    " * Returns the CSS var() string; resolved by the browser at runtime.",
    " */",
    "export function token(name: EulinxTokenName): string {",
    '  return `var(${name})`;',
    "}",
    "",
    "/** Re-export the source of truth type for downstream consumers. */",
    "export type { EulinxTokenNameSource };",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Contrast report + AA gate
// ---------------------------------------------------------------------------

type ContrastRow = {
  token: string;
  onSurface: string;
  requirement: "text-4.5" | "ui-3.0";
  dark: { ratio: number; passes: boolean; grade: string };
  light: { ratio: number; passes: boolean; grade: string };
};

function buildContrastReport(set: TokenSet): {
  rows: ContrastRow[];
  failures: ContrastRow[];
} {
  const rows: ContrastRow[] = [];
  const failures: ContrastRow[] = [];

  for (const s of set.semantics) {
    if (!s.contrast || !s.onSurface) continue;
    const dark = s.contrast[THEME_DARK];
    const light = s.contrast[THEME_LIGHT];
    if (!dark || !light) continue;

    const row: ContrastRow = {
      token: s.name,
      onSurface: s.onSurface,
      requirement: s.contrast[THEME_DARK].requirement,
      dark: { ratio: dark.ratio, passes: dark.passes, grade: dark.grade },
      light: { ratio: light.ratio, passes: light.passes, grade: light.grade },
    };
    rows.push(row);
    if (!dark.passes || !light.passes) failures.push(row);
  }

  return { rows, failures };
}

// ---------------------------------------------------------------------------
// Staleness sidecar
// ---------------------------------------------------------------------------

function sourceHash(): string {
  const srcPath = resolve(ROOT, tokenSet.generatedFrom);
  const content = existsSync(srcPath) ? readFileSync(srcPath, "utf8") : "";
  return createHash("sha256").update(content).digest("hex");
}

function readSidecar(): { sourceHash?: string; generatedAt?: string } {
  if (!existsSync(SIDECAR_PATH)) return {};
  try {
    return JSON.parse(readFileSync(SIDECAR_PATH, "utf8")) as {
      sourceHash?: string;
      generatedAt?: string;
    };
  } catch {
    return {};
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const checkOnly = process.argv.includes("--check");

  // 1. Validate usages are non-empty (Part01 invariant).
  for (const p of tokenSet.primitives) {
    if (p.usage.trim() === "") fail(`Primitive ${p.name} has an empty usage string.`);
  }
  for (const s of tokenSet.semantics) {
    if (s.usage.trim() === "") fail(`Semantic ${s.name} has an empty usage string.`);
  }
  for (const c of tokenSet.components) {
    if (c.usage.trim() === "") fail(`Component ${c.name} has an empty usage string.`);
  }

  // 2. Every theme binds every semantic role.
  for (const s of tokenSet.semantics) {
    for (const theme of tokenSet.themes) {
      if (s.bindings[theme] === undefined) {
        fail(`Semantic ${s.name} is missing a binding for theme "${theme}".`);
      }
    }
  }

  // 3. Contrast AA gate.
  const { rows, failures } = buildContrastReport(tokenSet);
  for (const f of failures) {
    process.stderr.write(
      `[tokens] CONTRAST FAIL: ${f.token} on ${f.onSurface} requires ${f.requirement} ` +
        `(dark ${f.dark.ratio}, light ${f.light.ratio})\n`,
    );
  }
  if (failures.length > 0) {
    fail(`${failures.length} semantic color pair(s) below AA floor.`);
  }

  const css = generateCss(tokenSet);
  const ts = generateTs(tokenSet);
  const report = {
    generatedAt: new Date().toISOString(),
    tokenSetVersion: tokenSet.version,
    themes: THEME_IDS,
    aaFloors: { text: AA_TEXT_FLOOR, ui: AA_UI_FLOOR },
    rows,
    summary: {
      total: rows.length,
      passed: rows.length - failures.length,
      failed: failures.length,
    },
  };

  if (checkOnly) {
    // CI mode: verify emitted files match what we would generate.
    const sidecar = readSidecar();
    const currentHash = sourceHash();
    if (sidecar.sourceHash !== currentHash) {
      fail(
        "Generated token files are STALE relative to tokens.source.ts. Re-run `npm run tokens`.",
      );
    }
    process.stdout.write("[tokens] --check: generated files are up to date.\n");
    return;
  }

  if (!existsSync(TOKENS_DIR)) mkdirSync(TOKENS_DIR, { recursive: true });
  writeFileSync(CSS_PATH, css, "utf8");
  writeFileSync(TS_PATH, ts, "utf8");
  writeFileSync(REPORT_PATH, JSON.stringify(report, null, 2) + "\n", "utf8");
  writeFileSync(
    SIDECAR_PATH,
    JSON.stringify({ sourceHash: sourceHash(), generatedAt: report.generatedAt }, null, 2) + "\n",
    "utf8",
  );

  process.stdout.write(
    `[tokens] wrote tokens.css, tokens.ts, contrast-report.json ` +
      `(${rows.length} contrast pairs, all passing AA).\n`,
  );
}

main();
